#!/bin/bash

cd Computer-Vision-2
git pull origin master
cd ..

echo Computer Vision 2 Update Complete

cd Parallel-Computing-2
git pull origin master
cd ..

echo Parallel Computing 2 Update Complete

